# Generated by Django 4.2 on 2024-06-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('title_en', models.CharField(default='', max_length=100, null=True)),
                ('title_ar', models.CharField(default='', max_length=100, null=True)),
                ('title_fr', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='medicine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producttype'),
        ),
    ]
